services: #Serviços
  database:
    image: "postgres:16.0-alpine3.18" #Mmagem que queremos baixar
    environment: #Variávies de ambiente
      POSTGRES_PASSWORD: "root"
    ports:
      #- "host:container" Relaciona uma porta no ambinete Host (mundo fora do container) e uma porta no guest (mundo dentro do container)
      - "5432:5432"
