services: #Serviços
  database:
    image: "postgres:16.0-alpine3.18" #Imagem que queremos baixar
    # environment: #Variávies de ambiente
    #   POSTGRES_PASSWORD: "root"
    env_file:
      - ../.env.development
    ports:
      #- "host:container" Relaciona uma porta no ambinete host (mundo fora do container) e uma porta no guest (mundo dentro do container) host:container
      - "5432:5432"
